# Config XMPP Server
xmpp_server = 'localhost'
web_port = 5222
url = "localhost"
jid_domain = "@" + xmpp_server

# FSM name states Central Federado
SETUP_STATE_AG = "SETUP_STATE"
RECEIVE_STATE_AG = "RECEIVE_STATE"
TRAIN_STATE_AG = "TRAIN_STATE"
SEND_STATE_AG = "SEND_STATE"
TEST_STATE_AG = "TEST_STATE"
RESPOND_STATE_AG = "RESPOND_STATE_AG"
IDLE_STATE_AG = "IDLE_STATE_AG"

CONSENSUS_LOGGER = "CONSENSUS_LOGGER"
MESSAGE_LOGGER = "MESSAGE_LOGGER"
WEIGHT_LOGGER = "WEIGHT_LOGGER"
TRAINING_LOGGER = "TRAINING_LOGGER"
EPSILON_LOGGER = "EPSILON_LOGGER"
TRAINING_TIME_LOGGER = "TRAINING_TIME_LOGGER"